language: java
sudo: true
jdk:
- oraclejdk8
install: true
script: ./gradlew -S -Pskip.signing build artifactoryPublish bintrayUpload leanpubBook -PbintrayUsername=$BINTRAY_USER
  -PbintrayApiKey=$BINTRAY_KEY
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
  - secure: iXqaplHcjbNJh7WD6IesYM91Lkr7FBWeykUpJIYNJRis9UcJonE8NVoikhaYXI3uNICsJOKKIqGL0fiFl8nFU43Xxp09HsyXmfBFgMZPp+7f2PJ/dJ3br+6xvwR4nCzS5TOvK6Ab7Jb19AqY5FcAKwcld/d7+hK+ox7O4mdj3eK5XmA5BccaqHN5CY6lTyFvEujA1ASpcXYRMPMPJFD5uRUwCx7ADCW90RcUE/BBVwPWSjEpBlopluAfdOGcU+X+fN4yI9oXxxsxoWoWyMp03jSbMnG+Ciu4m+TTAEQ2fdrrZvnkljdJR2HYei1dKhM0XMYhtCADwSSoAovXH5b5z7vVDLkyxKdcjJaxOrDTa5k+ENV9jqAPf8v57DpjzLBXzzO/E0fuVfu7D/T5K3yv+OY/QSJuq5wcdSXHayT1R+5mH0ydg5iFZKbaKnpjfdiR8gy0YOf7HJvHOmVoXlwMaZElLE2ILmtBBMqXh0G0ib0s7XXWMWPdQmaqD6W+ujGrOt824t0BgHaLBk+NqTswmVOVR3gcBTDvPchrpmHJXPOW1add78fCgiPtvHF8DhL+1YZJbuSSP5YoKyEzIRwvYA95KFmW1yqhezBfWVerRqc3oVgwGeliQgS4+LoTLzcd4tIzhzXeVjkn7V95LMgCCLwRyfc9H+Bw+SpZJ/UFj9U=
  - secure: E5IY86Ph8tV2uCMHYUDGWeYg/0xqe6n4ygtbkBETWJdCEMRE/WVF1fppH8MdwBUGMVg6PO7E9zdYcA4wAU218aPObyIakshr3FGn1j+dH3u47pHyG9KNpsa3HDZVlnGDv89PtjGl/ihU9Q5Yw+SHUWzEoAe1r8EQKEtuMZHSZUD5tRVFhrb81iuOY5cGXt34wEo/xNps42yePHt3J1xF0k2kuuCsFVCnV8ZarW6+Lv7rlDOx0uM0+qmGyXIGy/IMU2sG1+AepP9YKSX8ud3Lq1w3mXlev8TmwX48kuJrc/VhDQ8QRPqLkdTTiOxisxFdyZe8MmFnPtYbm4KAArn7A1gMS/K/7ZFYChiwg13CHPj13YZ7/ycx5REZOQktwhLGs7gAjKB2BCwTQrbf7W+bjOHprpP89g3haWAbtj/Ch/t536++bnIarM+Lo6/oByZAAMRHEXuaelfEGDAlBBFpdfhpriF972uGKWp5TnVWhW5xN0QcMezyeiKFD6RgMOZt8eshY6u+f32qDolbYkfk803PIxwz1bkYBY6DB2G8LJJV1wwdLYMQqgUabbUIKoZsHvRmz8A16R8Lv8ydYM2BCtOIN14c81ql/OPVuwmFRSIfVFldmuCRA9OJ5hL5TPB6a0BLR0f7OUZd159ZuqAXGT56GhRUCLvqNTlq1wmAe0U=
